export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const SET_START = "SET_START";
export const SET_START_AUTH = "SET_START_AUTH";

export const CREATE_COMPARISON_SUCCESS = "CREATE_COMPARISON_SUCCESS";
export const CREATE_COMPARISON_FAIL = "CREATE_COMPARISON_FAIL";

export const GET_PRICES_START = "GET_PRICES_START";
export const GET_PRICES_SUCCESS = "GET_PRICES_SUCCESS";
export const GET_PRICES_FAIL = "GET_PRICES_FAIL";

export const GET_COMPARISONS_SUCCESS = "GET_COMPARISONS_SUCCESS";
export const GET_COMPARISONS_FAIL = "GET_COMPARISONS_FAIL";
